select country.name from country where country.Code in (select CountryCode from countrylanguage where language = 'English');
select count(*) from country where region = 'Antarctica';
select name, Population from country order by population desc limit 5;
select name, lifeexpectancy from country order by lifeexpectancy asc limit 10;
select district, population from city order by population desc limit 5;
select countrycode,language from countrylanguage where percentage > 50;
select sum(GNP), region from country group by region order by sum(GNP) desc limit 1;
select sum(population)/ sum(surfacearea),sum(population), sum(surfacearea), continent from country group by continent order by sum(population)/ sum(surfacearea) desc limit 1;
select count(*) from countrylanguage where language = 'French';
select indepyear, name from country where indepyear < 1950 order by indepyear;